Add Configurable HTML Parser Wrappers for BeautifulSoup and Resiliparse
commoncrawl/cc-pyspark pull request #47
Opened 2024-12-27 07:34 UTC by silentninja

Fixes #43 

This PR introduces wrapper classes that provide a uniform API for common operations across two HTML parsers: `BeautifulSoup` and `Resiliparse`. The goal is to simplify switching between the parsers and ensure consistency in usage patterns.

Additionally, the PR adds support for configuring the HTML parser wrapper at runtime by introducing a new `--html_parser` option when submitting a Spark job. This allows users to specify their preferred parser dynamically during execution.

2024-12-27 20:06 UTC, silentninja commented
We can enhance this further by adding support for third-party HTML parser wrappers.  

The idea is to allow users to pass the path to a custom wrapper module as a runtime argument. This approach would enable developers to use community-contributed libraries without requiring modifications to the existing codebase.

### **Proposed Implementation**  
- Use Python's `importlib` to dynamically load the custom wrapper module at runtime.  
- Define an abstract base class that all custom wrapper classes must extend to ensure a consistent interface.  
- Add runtime validation to verify that the custom wrapper class correctly implements all required methods and adheres to the expected interface.  

It would be worth considering this when there is an interest in third-party wrappers

2024-12-30 18:49 UTC, wumpus commented
I like the idea of a wrapper that makes it easy to switch parsers.

2025-01-12 13:03 UTC, sebastian-nagel requested changes
Hi @silentninja, thanks for your contribution! I'll try it out soon.

2025-01-12 13:03 UTC, sebastian-nagel commented on requirements.txt
> +
Have you verified that it it possible to install and use FastWARC and Resiliparse with different versions?

2025-01-12 13:03 UTC, sebastian-nagel commented on sparkcc.py
> +        arg_parser.add_argument("--html_parser", default="beautifulsoup",
There's only one class which uses a HTML parser: CCIndexWordCountJob. Shouldn't the option be moved to the class were it is used?

If it's a global option, there may be confusion, such as "I thought WET files contain plain text from parsed HTML. Why I should specify a HTML parser?"

2025-01-23 20:53 UTC, silentninja commented on requirements.txt
> +
Hi @sebastian-nagel, thank you for the review! Just to clarify, Resiliparse has a strict version dependency on fastwarc and will throw up an error when installing incompatible versions

2025-01-23 21:45 UTC, silentninja commented on sparkcc.py
> +        arg_parser.add_argument("--html_parser", default="beautifulsoup",
> If it's a global option, there may be confusion

Yes that's correct. I will move it to that particular job.

2025-01-24 11:05 UTC, silentninja commented
Thanks for the review, @sebastian-nagel! I’ve made the changes. Could you please review them again?

2025-02-11 11:48 UTC, sebastian-nagel approved these changes
Thanks, @silentninja! Excellent!

I've successfully tested your PR and compared the word counts for both parsers. Nice to see that Resiliparse skips the boilerplate (or, at least, includes less boilerplate).

I'll merge the PR shortly. Thanks again!

2025-02-11 12:01 UTC, merged